export const SET_LOCALSTORAGE = 'SET_LOCALSTORAGE';

export const READY = 'READY';
export const READY_SUCCESS = 'READY_SUCCESS';
export const READY_ERROR = 'READY_ERROR';

export const PUSH_NOTIFICATION = 'PUSH_NOTIFICATION';
export const PUSH_NOTIFICATION_SUCCESS = 'PUSH_NOTIFICATION_SUCCESS';
export const PUSH_NOTIFICATION_ERROR = 'PUSH_NOTIFICATION_ERROR';