/*
 *  question constants
 *  
 */ 

// get question constants
 export const GET_QUESTION = 'GET_QUESTION';
 export const GET_QUESTION_SUCCESS = 'GET_QUESTION_SUCCESS';
 export const GET_QUESTION_ERROR = 'GET_QUESTION_ERROR';

 export const GET_OUT_OF_CONTEST = 'GET_OUT_OF_CONTEST';
 export const GET_OUT_OF_CONTEST_SUCCESS = 'GET_OUT_OF_CONTEST_SUCCESS';
 export const GET_OUT_OF_CONTEST_ERROR = 'GET_OUT_OF_CONTEST_ERROR';

 export const GET_STORAGE_OUT = 'GET_STORAGE_OUT';
 export const GET_STORAGE_OUT_SUCCESS = 'GET_STORAGE_OUT_SUCCESS';
 export const GET_STORAGE_OUT_ERROR = 'GET_STORAGE_OUT_ERROR';

 export const CLEAR_ALL_STATE = 'CLEAR_ALL_STATE';
