export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const GET_TOKEN = 'GET_TOKEN';
export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS';
export const GET_TOKEN_ERROR = 'GET_TOKEN_ERROR';

export const LOGOUT = 'LOGOUT';

export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_ERROR = 'GET_ALL_USERS_ERROR';

export const START_GAME = 'START_GAME';
export const UPDATE_USERS = 'UPDATE_USERS';

export const NEXT_CONTEST = 'NEXT_CONTEST';
export const NEXT_CONTEST_SUCCESS = 'NEXT_CONTEST_SUCCESS';
export const NEXT_CONTEST_ERROR = 'NEXT_CONTEST_ERROR';

export const ADD_PLAYERS = 'ADD_PLAYERS';
export const ADD_PLAYERS_SUCCESS = 'ADD_PLAYERS_SUCCESS';
export const ADD_PLAYERS_ERROR = 'ADD_PLAYERS_ERROR';

export const CLEAR_ADD_PLAYER_STATE = 'CLEAR_ADD_PLAYER_STATE';

export const UPDATE_LOGIN_LIST = 'UPDATE_LOGIN_LIST';

export const INITIAL_GAME = 'INITIAL_GAME';